# Generated by Django 4.0.4 on 2022-10-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('west', 'WEST'), ('east', 'EAST'), ('south', 'SOUTH'), ('alaska', 'ALASKA'), ('hawaii', 'HAWAII'), ('midwest', 'MIDWEST')], max_length=7)),
            ],
        ),
    ]
