# Generated by Django 4.0.4 on 2022-10-23 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0002_contribution_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date_received',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
